import { expect, test } from '@playwright/test';

/**
 * C2-T-003 — generateMetadata Migration
 *
 * Scenarios derived from the task "User test":
 *   1. All 5 pages produce correct page-specific titles via generateMetadata
 *   2. robots.txt is served correctly at /robots.txt
 *   3. sitemap.xml is served correctly at /sitemap.xml
 *   4. All 5 pages render correctly in light mode
 *   5. All 5 pages render correctly in dark mode
 *   6. Mobile navigation menu opens and closes at mobile viewport width
 *   7. Active navigation link is highlighted in Header on each route
 *   8. Active navigation link is highlighted in Footer on each route
 */

test.describe('C2-T-003 — generateMetadata Migration', () => {
	/**
	 * GIVEN: The dev server is running
	 * WHEN: I visit each route
	 * THEN: Each page's <title> matches the page-specific metadata generated by generateMetadata
	 */
	test('all five pages have correct generateMetadata titles', async ({
		page,
	}) => {
		const routes = [
			{ path: '/', title: 'Dinesh Haribabu' },
			{ path: '/about', title: 'About me — Dinesh Haribabu' },
			{ path: '/projects', title: 'Projects — Dinesh Haribabu' },
			{ path: '/blog', title: 'Blog — Dinesh Haribabu' },
			{ path: '/uses', title: 'Uses — Dinesh Haribabu' },
		];

		for (const { path: route, title } of routes) {
			await page.goto(route);
			await expect(page).toHaveTitle(title);
		}
	});

	/**
	 * GIVEN: The dev server is running
	 * WHEN: I fetch /robots.txt
	 * THEN: The response is 200 with valid robots.txt content (User-Agent, Allow, Sitemap)
	 */
	test('robots.txt is served correctly', async ({ page }) => {
		const response = await page.goto('/robots.txt');
		expect(response?.status()).toBe(200);
		const content = (await response?.text()) ?? '';
		expect(content).toContain('User-Agent');
		expect(content).toContain('Allow');
		expect(content).toContain('/');
		expect(content).toContain('Sitemap: https://dineshharibabu.in/sitemap.xml');
	});

	/**
	 * GIVEN: The dev server is running
	 * WHEN: I fetch /sitemap.xml
	 * THEN: The response is 200 with valid sitemap.xml containing all five routes
	 */
	test('sitemap.xml is served correctly', async ({ page }) => {
		const response = await page.goto('/sitemap.xml');
		expect(response?.status()).toBe(200);
		const content = await page.content();
		expect(content).toContain('https://dineshharibabu.in/');
		expect(content).toContain('/about');
		expect(content).toContain('/projects');
		expect(content).toContain('/blog');
		expect(content).toContain('/uses');
	});

	/**
	 * GIVEN: The dev server is running in light mode
	 * WHEN: I visit each route
	 * THEN: All 5 pages render their content without errors in light mode
	 */
	test('all pages render correctly in light mode', async ({ page }) => {
		await page.evaluate(() => {
			document.documentElement.classList.remove('dark');
		});

		const routes = [
			{ path: '/', heading: 'Dinesh Haribabu' },
			{ path: '/about', heading: /about me/i },
			{ path: '/projects', heading: /GitHub Projects/i },
			{ path: '/blog', heading: /Blog Posts/i },
			{ path: '/uses', heading: /Uses/i },
		];

		for (const { path: route, heading } of routes) {
			await page.goto(route);
			await expect(
				page.getByRole('heading', { level: 1, name: heading })
			).toBeVisible();
			await expect(page.getByRole('navigation')).toBeVisible();
			await expect(page.locator('footer')).toBeVisible();
		}
	});

	/**
	 * GIVEN: The dev server is running and dark mode is enabled
	 * WHEN: I visit each route
	 * THEN: All 5 pages render correctly with dark mode styles applied
	 */
	test('all pages render correctly in dark mode', async ({ page }) => {
		await page.emulateMedia({ colorScheme: 'dark' });

		const routes = [
			{ path: '/', heading: 'Dinesh Haribabu' },
			{ path: '/about', heading: /about me/i },
			{ path: '/projects', heading: /GitHub Projects/i },
			{ path: '/blog', heading: /Blog Posts/i },
			{ path: '/uses', heading: /Uses/i },
		];

		for (const { path: route, heading } of routes) {
			await page.goto(route);
			await expect(
				page.getByRole('heading', { level: 1, name: heading })
			).toBeVisible();
			await expect(page.getByRole('navigation')).toBeVisible();
			await expect(page.locator('footer')).toBeVisible();
		}
	});

	/**
	 * GIVEN: I am on a page at mobile viewport width
	 * WHEN: I tap the hamburger menu button
	 * THEN: The mobile navigation menu opens and closes correctly
	 */
	test('mobile navigation menu opens and closes', async ({ page }) => {
		await page.setViewportSize({ width: 375, height: 812 });

		await page.goto('/');

		const menuButton = page.getByRole('button', { name: /menu/i });

		await expect(menuButton).toBeVisible();
		await expect(page.locator('#mobile-menu')).not.toBeVisible();

		await menuButton.click();

		const mobileMenu = page.locator('#mobile-menu');
		await expect(mobileMenu).toBeVisible();
		await expect(
			mobileMenu.getByRole('link', { name: 'About me' })
		).toBeVisible();
		await expect(
			mobileMenu.getByRole('link', { name: 'Projects' })
		).toBeVisible();
		await expect(mobileMenu.getByRole('link', { name: 'Blog' })).toBeVisible();
		await expect(mobileMenu.getByRole('link', { name: 'Uses' })).toBeVisible();

		await menuButton.click();

		await expect(mobileMenu).not.toBeVisible();
	});

	/**
	 * GIVEN: I am on any page (not the home page — home has no nav links in header)
	 * WHEN: I look at the Header navigation
	 * THEN: The active navigation link is highlighted with the active class
	 */
	test('active navigation link is highlighted in Header on each route', async ({
		page,
	}) => {
		const routes = [
			{ path: '/about', activeLabel: 'About me' },
			{ path: '/projects', activeLabel: 'Projects' },
			{ path: '/blog', activeLabel: 'Blog' },
			{ path: '/uses', activeLabel: 'Uses' },
		];

		for (const { path: route, activeLabel } of routes) {
			await page.goto(route);

			const headerNav = page.locator('nav').first();

			await expect(
				headerNav.getByRole('link', { name: activeLabel })
			).toHaveClass(/bg-stone-300/);
		}
	});

	/**
	 * GIVEN: I am on any page
	 * WHEN: I look at the Footer navigation
	 * THEN: The active navigation link is highlighted with the active class
	 */
	test('active navigation link is highlighted in Footer on each route', async ({
		page,
	}) => {
		const routes = [
			{ path: '/about', activeLabel: 'About me' },
			{ path: '/projects', activeLabel: 'Projects' },
			{ path: '/blog', activeLabel: 'Blog' },
			{ path: '/uses', activeLabel: 'Uses' },
		];

		for (const { path: route, activeLabel } of routes) {
			await page.goto(route);

			const footer = page.locator('footer');

			await expect(footer.getByRole('link', { name: activeLabel })).toHaveClass(
				/font-semibold/
			);
		}
	});
});
