name: Bump version (on merge)

on:
  push:
    branches: 
      - main 

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checks out repository code
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm ci

      - name: Initialize Git user
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: Log git status
        run: git status
      
      - name: Run release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
